### PR TITLE
pentomino.py

### PR DESCRIPTION
**Pull request by ay4me**
I finished the implementation of the first methods.
The only given test that fails compares coos that are actually equal but in wrong order, which I think doesn't really need fixing.

### CODE REVIEW

**Comment by julian-upc** [comment]
Ok, but then you should rewrite the test. Remember, there is no sacred code! 

Also, see https://github.com/julian-upc/2015-algorithms/issues/11

**Comment by ay4me** [comment]
So now it has a subdirectory and I changed the test and also after talking about it in class, I renewed the normalize.methods, since they did not exactly do what was wanted.

**Comment by julian-upc** [comment]
Please restore the original pentominos.py! You probably ```git mv``` ed it to your subdirectory, but that means it's gone for everyone else.

**Comment by ay4me** [comment]
Ok, I did so

**Comment by ay4me** [comment]
I completed the incidence-matrix, the test runs through.
I am not so happy with the naming of the incidence-cells since it is not unique and the numbers do not correspond to the size see #17 .

**Pull request merged**
