### PR TITLE
Coxeter Group Algorithm

### PR DESCRIPTION
**Pull request by ay4me**
I implemented the basic algorithm.
Since it was in the specifications I use the in- and output files.

### CODE REVIEW

**Comment by ay4me** [comment]
I changed what you suggested and also added some try for Dn.

**Comment by julian-upc** [comment]
ok, but your changes don't show up in this pull request.

**Comment by ay4me** [comment]
Well, they do, but they are in the wrong commit "matrix for A". I am not sure how that happened, the commit it was ment to be in is empty, i guess I forget to add the file.

**Comment by julian-upc** [comment]
oh, sorry, I hadn't seen the new commits. My bad.

**Pull request merged**
